### ISSUE TITLE
Can't run example from README under macOS

### ISSUE THREAD

**Issue by pkrog** [phnmnl/docker-nmrmlconv#1]
The following command:
`docker run -ti -v /usr/src/nmrML/examples/MTBLS1/FIDs/ADG10003u_007/10/:/src -v $PWD:/data phnmnl/nmrmlconv:latest -l create -b -z -t bruker -i /src/ -o /data/ADG10003u_007_10.nmrml`

gives the following output:

> ACQUISITION_FILE not available or readable: /src/acqus

**Comment by korseby** [comment]
Where are your source files located in? If they are in the current directory and are .nmrml, try this:

`docker run -ti -v $PWD:/data phnmnl/nmrmlconv:latest -l create -b -z -t bruker -i /data/*.nmrml -o /data/test.nmrml`

**Comment by pkrog** [comment]
Ok, my fault, I saw that nmrML repos was already cloned inside the docker image, and didn't look at the first -v option. With the following command:
`docker run -ti -v $PWD:/data phnmnl/nmrmlconv:latest -l create -b -z -t bruker -i /usr/src/nmrML/examples/MTBLS1/FIDs/ADG10003u_007/10/ -o /data/ADG10003u_007_10.nmrml`
It now works perfectly.

**Comment by pkrog** [comment]
And with `docker run -ti -v $PWD/nmrML/examples/MTBLS1/FIDs/ADG10003u_007/10/:/src -v $PWD:/data phnmnl/nmrmlconv:latest -l create -b -z -t bruker -i /src/ -o /data/ADG10003u_007_10.nmrml` too.
