### ISSUE TITLE
nmrMLpipe error while running docker in Galaxy

### ISSUE THREAD

**Issue by pkrog** [phnmnl/docker-nmrmlconv#2]
nmrMLpipe: Error while parsing the command line: /home/vagrant/galaxy/config/job_working_directory/000/6/tool_script.sh

usage: nmrMLpipe
 -h,--help                               prints the help content
 -l,--launch <create|proc|peaks|atoms>   what to lanch: create, proc
 -v,--version                            prints the version

**Comment by korseby** [comment]
Hi @pierrickrogermele , I'm back from vacation. Can you post the contents of the tool_script.sh from the galaxy job_working_directory?
